### PR TITLE
Added projects & members

### PR DESCRIPTION
**Pull request by nithmanoj**
for members used index.php style but removed twitter. Just added link of projects.php

### CODE REVIEW

**Comment by pranavk** [comment]
Good work overall ! 

Few comments - 
* You need to squash the last two commits.
* As of now, I think it would be better to hide the projects link from glugnith homepage because there is nothing relevant there at the moment.
* Fix the commit message, spelling typo there, it says 'extraa'. s/extraa/extra/

**Comment by pranavk** [comment]
I don't have any problem with projects page shown up in the website, but there is nothing in there but few broken links.

@rohanjaswal2507  Was it decided in the meeting to show the project page anyways ?

**Comment by pranavk** [comment]
One more thing 

Good, but seems you and @lokeshh are working on same thing. 
It would be better to work on two separate things in future.

**Comment by nithmanoj** [comment]
Squashed the commits. @sagarkarira Sir said for projects link.

**Comment by rohanjaswal2507** [comment]
@nithmanoj Why did you remove tweets from index.php?

**Comment by nithmanoj** [comment]
I removed that from members.php , As it is bottom of page & table was long. If by chance it got removed from index.php that's mistake

**Comment by nithmanoj** [comment]
I removed that from members.php , As it is bottom of page & table was long. If by chance it got removed from index.php that's mistake

**Comment by rohanjaswal2507** [comment]
@nithmanoj please revert the changes you made to index.php. We need tweets there.

**Comment by nithmanoj** [comment]
Sir added tweets. Sorry for that mistake...

**Comment by pranavk** [comment]
Please don't include projects page as of now, since we don't have any projects to showcase as of this writing.

@nithmanoj Also, since it was a mistake on your behalf, deleting tweets, squash this into your previous commit.

**Comment by pranavk** [comment]
So, just adding a commit adding the members page should do fine. Please submit a new PR adding the members page only.

**Pull request closed without merging**
