### PR TITLE
Request form for glug mail alias

### PR DESCRIPTION
**Pull request by rohanjaswal2507**

### CODE REVIEW

**Comment by pranavk** [comment]
We also need this information :
Desired glug email alias.

Eg : If you are applying then, what email alias you desire (say rohan@glug.nith.ac.in) which should be forwarded to your email address provided there.

So it is missing desired glug email alias field

**Comment by rohanjaswal2507** [comment]
okay will add this.

**Comment by rohanjaswal2507** [comment]
@pranavk did you see that check_email function ?

**Comment by pranavk** [comment]
merged and pushed.

**Pull request closed without merging**
