### PR TITLE
Add new background logo 

### LINKED ISSUE #19: New logo on website
We have a new logo on facebook glugnith page. We need to replace the old logo on the website with this new logo such that it doesn't look awkward. I remember last time we did this, it was looking awkward changing the whole orientation of the website.

### PR DESCRIPTION
**Pull request by lokeshh**
Fixes #19 

Adds a new background logo taken from Facebook page.

### CODE REVIEW

**Comment by lokeshh** [comment]
Heres how it looks like
IMG

**Comment by divyanshu013** [comment]
Can you scale this using only height or width. It looks out of proportions.

**Comment by lokeshh** [comment]
It doesn't look good if I keep it in original proportion.

**Comment by divyanshu013** [comment]
Can you attach a screenshot? Also try experimenting with the positioning. Although I was hoping that you guys could do something about issue #33 which would be better 😉

**Comment by lokeshh** [comment]
I have made some changes in the CSS so it looks in proportion and also looks good. Here's the screenshoot:

IMG

Does this look good now?

**Comment by sagarkarira** [comment]
I don't know, this is looking slightly odd. The height should be small. @divyanshu013  what do you think?

**Comment by divyanshu013** [comment]
Yeah, looking a bit odd. How about you move the navbar to the top and move the logo to the left section where "What is GNU?" is mentioned?

**Comment by lokeshh** [comment]
@divyanshu013 How about I try to adapt the home page to a bootstrap template? This would also solve this issue and also make the website beautiful and responsive for mobile. Or should I make the logo change first? Please let me know.

**Comment by lokeshh** [comment]
One more question: I do not know PHP. Would knowledge of PHP be required in installing a bootstrap template to the home page? I suppose we just need to place the CSS and javascipt at appropriate places taken from a bootstrap template and the name the elements with `id`s and `classes` in the html. The knowledge of PHP won't be required. Right?

**Comment by divyanshu013** [comment]
I think you guys might need to start from scratch on a bootstrap template instead of adapting the current site to bootstrap, that would be faster; just get a good bootstrap template (there are many freely available and can be tweaked as needed). The logo change is up to you. As for your latter question, unless you're using a PHP framework like Laravel, you won't need knowledge of PHP. Perhaps you guys should discuss this in a meeting with your seniors.

**Comment by sagarkarira** [comment]
@lokeshh  You should look into this. [Lektor](https://www.getlektor.com/) or [Grav](https://getgrav.org/) can help you build the entire website in a week. Also they have many different templates.

**Comment by lokeshh** [comment]
@sagarkarira `Lektor` seems great.

Please clarify one thing, what does it mean when we say we are looking to build the entire website? Does it also mean rebuilding "gluPaste", "Wiki", "gluBlog", etc. or just building the basic pages like homepage, contact page, etc. of the website?

**Comment by sagarkarira** [comment]
@lokeshh I think we should move to  gitter or irc to discuss this, as this discussion has nothing to do this with this issue. Ping me where ever you feel comfortable to talk to.

**Comment by divyanshu013** [comment]
gluPaste and gluBlog are working great, we're just talking about the site for #33

**Comment by lokeshh** [comment]
@divyanshu013 I just had a chat with @sagarkarira and he cleared my doubts. I've started the work on the website at https://github.com/lokeshh/upgrade_glugnith

**Comment by divyanshu013** [comment]
Closing this PR till we've the new site ready.

**Pull request closed without merging**
